import { NextRequest, NextResponse } from 'next/server';

// Document export API
// Generates PDF, Word, Excel, or ZIP bundles

export async function POST(request: NextRequest) {
  try {
    const { format, formData } = await request.json();

    if (!format || !formData) {
      return NextResponse.json({ error: 'Format and formData are required' }, { status: 400 });
    }

    // For now, generate a simple text file as placeholder
    // In production, use jspdf, docx, exceljs libraries

    const generateValuationMemo = () => {
      return `
VALUATION REPORT: ${formData.valuation?.systemName || 'QréativeLab AI/Automation System'}
================================================================================

1. EXECUTIVE SUMMARY
-------------------
System Name: ${formData.valuation?.systemName || 'N/A'}
Fair Market Value: $10,000,000 CAD
Valuation Date: ${new Date().toISOString().split('T')[0]}
Purpose: IP contribution for incorporation Class A shares

2. SYSTEM OVERVIEW
------------------
Core Capabilities:
${formData.valuation?.coreFeatures || 'N/A'}

Unique Differentiation:
${formData.valuation?.uniqueAdvantages || 'N/A'}

Current State: ${formData.valuation?.developmentStatus || 'N/A'}

3. VALUATION METHODOLOGY
------------------------
Cost Approach - Rebuild Cost: $${formData.valuation?.rebuildCost || '10,000,000'}
Income Approach - Revenue Projections:
  Year 1: $${formData.valuation?.revenueYear1 || 'N/A'}
  Year 2: $${formData.valuation?.revenueYear2 || 'N/A'}
  Year 3: $${formData.valuation?.revenueYear3 || 'N/A'}

4. CONCLUSION
-------------
Based on the cost approach, income approach, and comparable market analysis,
the Fair Market Value of the system is: $10,000,000 CAD

================================================================================
Generated by QréativeLab Legal Document Builder
Date: ${new Date().toISOString()}
      `.trim();
    };

    const generateCapTable = () => {
      return `
CAP TABLE v0.1 - QréativeLab Inc.
================================================================================

SHAREHOLDER INFORMATION
-----------------------
Shareholder: ${formData.capTable?.founderName || 'N/A'}
Address: ${formData.capTable?.founderAddress || ''}, ${formData.capTable?.founderCity || ''}, ${formData.capTable?.founderProvince || ''} ${formData.capTable?.founderPostalCode || ''}

SHARE STRUCTURE
---------------
Class A (Super-Voting):
  Authorized: Unlimited
  Issued: ${formData.capTable?.classAShares || '1,000'}
  Percentage: 100%
  Votes per Share: 10
  Total Votes: ${(parseInt(formData.capTable?.classAShares || '1000') * 10).toLocaleString()}
  Grant Date: ${formData.capTable?.incorporationDate || 'N/A'}
  Strike Price: IP valued at $10,000,000
  Vesting: Fully vested (founder)

Reserved Classes (Not Yet Issued):
  Class B: Co-founders (1 vote/share, PSU vesting)
  Class C: Series A Investors (1 vote/share, liquidation preference)
  Class D: Advisors (non-voting, 24-month vesting)
  Class E: Employee Options (non-voting, $0.01 strike)

================================================================================
Generated by QréativeLab Legal Document Builder
Date: ${new Date().toISOString()}
      `.trim();
    };

    const generateArticles = () => {
      return `
ARTICLES OF INCORPORATION
QréativeLab Inc.
================================================================================

FORM 1 - ARTICLES OF INCORPORATION
CANADA BUSINESS CORPORATIONS ACT (CBCA)

1. NAME OF CORPORATION
----------------------
${formData.articles?.companyName || 'QréativeLab Inc.'}

2. REGISTERED OFFICE
--------------------
Address: ${formData.articles?.registeredAddress || 'N/A'}
City: ${formData.articles?.registeredCity || 'N/A'}
Province: ${formData.articles?.registeredProvince || 'QC'}
Postal Code: ${formData.articles?.registeredPostalCode || 'N/A'}

3. SHARE CLASSES
----------------
The corporation is authorized to issue shares in five (5) classes:

CLASS A - COMMON SHARES (Founder Super-Voting)
  • Voting rights: 10 votes per share
  • Dividend rights: Equal pro-rata
  • Liquidation: Pro-rata after preferences
  • Transfer restrictions: With founder exemption

CLASS B - CO-FOUNDER SHARES
  • Voting rights: 1 vote per share
  • Subject to PSU vesting
  • Transfer restrictions: Restricted

CLASS C - SERIES A PREFERRED SHARES
  • Reserved for future Series A investors
  • Liquidation preference: 1x non-participating

CLASS D - ADVISOR SHARES
  • Non-voting (advisory only)
  • Vesting: 24 months

CLASS E - EMPLOYEE OPTIONS
  • Reserved for employee equity pool
  • Strike price: $0.01

4. RESTRICTIONS ON SHARE TRANSFERS
----------------------------------
  • Right of First Refusal (ROFR)
  • Co-sale (Drag-along) rights
  • Founder exemption for Class A

5. DIRECTORS
------------
Initial Director(s): ${formData.articles?.directorNames || 'N/A'}

6. RESTRICTIONS ON BUSINESS
---------------------------
None.

================================================================================
Generated by QréativeLab Legal Document Builder
Date: ${new Date().toISOString()}
      `.trim();
    };

    const generateLawyerMemo = () => {
      return `
MEMO POUR AVOCAT
================================================================================

À: [Nom de l'avocat]
De: ${formData.capTable?.founderName || 'Founder'}
Date: ${new Date().toISOString().split('T')[0]}
Re: QréativeLab Inc. - Documents d'incorporation pour révision

Cher Maître,

Je vous transmets les documents suivants pour révision avant dépôt auprès d'ISED:

DOCUMENTS INCLUS:
1. IP Valuation Memo (3-5 pages)
2. Technical Specification (5-10 pages)
3. Cap Table v0.1 (Excel)
4. IP Contribution Agreement (3-5 pages)
5. Articles of Incorporation (15-20 pages)
6. Bylaws (8-10 pages)
7. Shareholders' Agreement (10-15 pages)

POINTS CLÉS À VÉRIFIER:
□ Structure 5 classes d'actions conforme au CBCA
□ Ratio de votes 10:1 pour Class A (super-voting founder)
□ ITA s.85.1 pour contribution IP non-imposable
□ ROFR et restrictions de transfert
□ Langage légal optimal

TIMELINE SOUHAITÉE:
- Révision: 2-3 heures
- Corrections: 1-2 jours
- Dépôt ISED: Semaine prochaine

Merci de votre collaboration.

${formData.capTable?.founderName || 'Founder'}
QréativeLab Inc.

================================================================================
Generated by QréativeLab Legal Document Builder
Date: ${new Date().toISOString()}
      `.trim();
    };

    // Combine all documents
    const allDocuments = `
${'='.repeat(80)}
QRÉATIVELAB INC. - INCORPORATION DOCUMENTS BUNDLE
${'='.repeat(80)}

TABLE OF CONTENTS:
1. IP Valuation Memo
2. Cap Table v0.1
3. Articles of Incorporation
4. Memo pour Avocat

${'='.repeat(80)}

${generateValuationMemo()}

${'='.repeat(80)}

${generateCapTable()}

${'='.repeat(80)}

${generateArticles()}

${'='.repeat(80)}

${generateLawyerMemo()}

${'='.repeat(80)}
END OF DOCUMENTS
${'='.repeat(80)}
    `.trim();

    // Return as text file (in production, use proper PDF/DOCX generation)
    const encoder = new TextEncoder();
    const content = encoder.encode(allDocuments);

    return new NextResponse(content, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="qreativelab-incorporation-documents.txt"`
      }
    });

  } catch (error) {
    console.error('Export API error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
